### PR TITLE
Create Tutorial_of_making_different_types_of_interactive_graphs.Rmd

### PR DESCRIPTION
**Pull request by shuminsong**
I have finished an pushed my tutorial of making different types of interactive graphs in my remote repo.

### CODE REVIEW

**Comment by lauradls** [comment]
The `.Rmd` filename can only contain lowercase letters. Please update.

**Review by lauradls — CHANGES_REQUESTED** [review]
The .Rmd filename can only contain lowercase letters. Please update.

**Comment by shuminsong** [comment]
Hi lauradis,

I have updated my .Rmd file name and pushed it to my local branch.

Best,
Shumin

**Comment by lauradls** [comment]
Thank you for your contribution! 🎉

**Pull request merged**
