### PR TITLE
Color deficiency

### PR DESCRIPTION
**Pull request by mwreed1**
fixed image calls

### CODE REVIEW

**Comment by lauradls** [comment]
- Please update all {r xxx} expressions to {r}. For example, `{r load-pkgs, include=F}` to this` {r}`
- Remove:
load.packages("tidyverse")
load.packages("ggokabeito")

**Review by lauradls — CHANGES_REQUESTED** [review]
Please update all {r xxx} expressions to {r}. For example, {r load-pkgs, include=F} to this {r}
Remove:
load.packages("tidyverse")
load.packages("ggokabeito")

**Comment by lauradls** [comment]
Thank you for your contribution! 🎉

**Comment by lauradls** [comment]
Hi @mwreed1 ! Could you please make one last change to the `_bookdown.yml `file? Just add .Rmd to 'color_deficiency' so it reads as 'color_deficiency.Rmd'. Let me know once done!

**Comment by mwreed1** [comment]
> 

I checked out the `_bookdown.yml` file and it seems like file name has been fixed.

**Pull request merged**
