### PR TITLE
Added bestparcoords Rmd file

### PR DESCRIPTION
**Pull request by danyoungday**
Requires custom package from here: devtools::install_github("ShubhamKaushal15/bestparcoords")

### CODE REVIEW

**Comment by philkim72** [comment]
Does your page also require the GGally package installed?

**Comment by danyoungday** [comment]
> 

Our package itself uses GGally so I believe it doesn't need to be explicitly installed for the Rmd.

**Comment by philkim72** [comment]
OK understood.  I need to check whether the installation from github requires special treatment.  So I will merge once I get an answer from the professor.

**Comment by jtr13** [comment]
Yes, `ShubhamKaushal15/bestparcoords` needs to be added to the `Remotes` section in `DESCRIPTION` *and* `bestparcoords` to `Suggests` (as usual).

**Comment by philkim72** [comment]
Thank you for your contribution! :tada:

**Pull request merged**
