### PR TITLE
create plotly cheatsheet

### PR DESCRIPTION
**Pull request by yichuang25**
cheatsheet for plotly

### CODE REVIEW

**Comment by rohansheelvant** [comment]
Hi! Please rename the filename such that it only contains lowercase letters and underscores.

**Comment by rohansheelvant** [comment]
Also please modify the second line in .Rmd file. The second line should be blank. 

More instructions of submission, follow these steps: https://jtr13.github.io/cc22mw/github-submission-instructions.html

**Comment by yichuang25** [comment]
I already renamed and adjust the format of the file.

**Comment by rohansheelvant** [comment]
Thanks for your contribution! 🎉

**Pull request merged**
