### PR TITLE
Geocomputationinr Merge

### PR DESCRIPTION
**Pull request by ShrujanPenmetsa**

### CODE REVIEW

**Comment by philkim72** [comment]
Actually, since you reference the files in your own github repo, you don't need to include the two files in the resources folder.  Please delete the folder and the two files.

**Review by philkim72 — CHANGES_REQUESTED** [review]
Actually, since you reference the files in your own github repo, you don't need to include the two files in the resources folder.  Please delete the folder and the two files.

**Comment by philkim72** [comment]
Also please follow the following instructions:

Include any library() statements at the top of your .Rmd file, below the title, name, and setup, but above any content.

**Review by philkim72 — CHANGES_REQUESTED** [review]
Also please follow the following instructions:

Include any library() statements at the top of your .Rmd file, below the title, name, and setup, but above any content.

**Comment by ShrujanPenmetsa** [comment]
Have made the changes to setup , deleted the folders and added a google drive link. Can you please check

**Comment by philkim72** [comment]
Thank you for your contribution! :tada:

**Comment by philkim72** [comment]
The spDataLarge is not installing properly in our environment.  ShrujanPenmetsa, can you provide the exact installation instructions you used to install the package?

**Comment by jtr13** [comment]
@philkim72 Please see my comment here -- https://github.com/jtr13/cc22mw/issues/60.

**Comment by philkim72** [comment]
Yes, I see it.

**Pull request merged**
